addSbtPlugin("com.timushev.sbt"   % "sbt-updates"          % "0.3.1")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.6")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "1.2.0")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.16.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.2.0")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.12.0")

addSbtPlugin("com.jsuereth"      % "sbt-pgp"              % "1.1.1")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"         % "2.0")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"          % "0.3.1")
addSbtPlugin("com.github.gseitz" % "sbt-release"          % "1.0.9")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.12.1")
